namespace SmartEnum.Generators;

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using SmartEnum.Generators.Models;

public sealed partial class SmartEnumGenerator
{
	private void GenerateDerivedClassConstructorAndFactoryMethod(SourceProductionContext context, GenerationModel model)
	{
		if (model.DerivedClass is null || model.DerivedClass.IsAbstract)
		{
			return;
		}

		string constructorParameters = GeneratorHelpers.GenerateConstructorParameters(model.Properties);
		string constructorArguments = GeneratorHelpers.GenerateConstructorArguments(model.Properties);

		string constructedText = $$"""
			// <auto-generated />
			{{GeneratorHelpers.GenerateNamespace(model.DerivedClass)}}
			public partial class {{model.DerivedClass.ToDisplayString()}}
			{
				private {{model.DerivedClass.ToDisplayString()}}({{constructorParameters}}) : base({{constructorArguments}}) { }

				/// <summary>
				/// CAUTION: This method bypasses all domain rules that may exist and may create invalid business state. Use it only for state transfer like EF Core -> Domain model.
				/// </summary>
				public {{model.DerivedClass.ToDisplayString()}} ConstructUnvalidatedObject({{constructorParameters}}) => new({{constructorArguments}});
			}
			""";

		context.AddSource($"{model.DerivedClass}.g.cs", SourceText.From(constructedText, Encoding.UTF8));
	}
}