namespace SmartEnum.Generators;

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using SmartEnum.Generators.Models;

public sealed partial class SmartEnumGenerator
{
	private void GenerateBaseClassConstructorAndFactoryMethod(SourceProductionContext context, GenerationModel model, ImmutableArray<GenerationModel> models)
	{
		if (model.DerivedClass is not null)
		{
			return;
		}

		string constructorParameters = GeneratorHelpers.GenerateConstructorParameters(model.Properties);
		string constructorArguments = GeneratorHelpers.GenerateConstructorArguments(model.Properties);
		string initializationList = GeneratorHelpers.GenerateInitializationList(model.Properties);
		string keyParameterName = string.Empty;
		foreach (GenerationModel derivedModel in models)
		{
			if (derivedModel.DerivedClass is null)
			{
				continue;
			}
		}

		string keyParameter = $"{model.KeyField.Type.ToDisplayString()} {keyParameterName}";

		string switchExpression = string.Empty;
		foreach (GenerationModel derivedModel in models)
		{
			if (derivedModel.DerivedClass is null)
			{
				continue;
			}

			switchExpression += $"{derivedModel.DerivedClass.ToDisplayString()}. => new {derivedModel.DerivedClass.Name}({constructorArguments}),\n";
		}

		string constructedText = $$"""
			// <auto-generated />
			{{GeneratorHelpers.GenerateNamespace(model.BaseClass)}}
			public abstract partial class {{model.BaseClass.ToDisplayString()}}
			{
				protected {{model.BaseClass.ToDisplayString()}}({{constructorParameters}})
				{
					{{initializationList}}
				}

				/// <summary>
				/// CAUTION: This method bypasses all domain rules that may exist and may create invalid business state. Use it only for state transfer like EF Core -> Domain model.
				/// </summary>
				public {{model.BaseClass.ToDisplayString()}} ConstructUnvalidatedObject({{constructorParameters}}{{keyParameter}}) => {{keyParameterName}} switch
				{
					{{switchExpression}}_ => throw new InvalidOperationException();
				};
			}
			""";

		context.AddSource($"{model.BaseClass}.g.cs", SourceText.From(constructedText, Encoding.UTF8));
	}
}