namespace SmartEnum.Generators;

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using SmartEnum.Generators.Models;

public sealed partial class SmartEnumGenerator
{
	private void GenerateDerivedAbstractClassConstructor(SourceProductionContext context, GenerationModel model)
	{
		if (model.DerivedClass is null || !model.DerivedClass.IsAbstract)
		{
			return;
		}

		string constructorParameters = GeneratorHelpers.GenerateConstructorParameters(model.Properties);
		string constructorArguments = GeneratorHelpers.GenerateConstructorArguments(model.Properties);

		string constructedText = $$"""
			// <auto-generated />
			{{GeneratorHelpers.GenerateNamespace(model.DerivedClass)}}
			public abstract partial class {{model.DerivedClass.ToDisplayString()}}
			{
				protected {{model.DerivedClass.ToDisplayString()}}({{constructorParameters}}) : base({{constructorArguments}}) { }
			}
			""";

		context.AddSource($"{model.DerivedClass}.g.cs", SourceText.From(constructedText, Encoding.UTF8));
	}
}