namespace SmartEnum.Generators;

using Microsoft.CodeAnalysis;

[Generator(LanguageNames.CSharp)]
public sealed class SmartEnumAttributeGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context) => context
		.RegisterPostInitializationOutput(output => output.AddSource("SmartEnumAttribute.g.cs", """
				// <auto-generated />
				namespace SmartEnum;
				
				using System;

				[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
				internal sealed class SmartEnumAttribute<TKey> : Attribute
				{
					public string KeyName { get; set; }

					public SmartEnumAttribute(string keyName) => this.KeyName = keyName;
				}
				"""));
}