namespace SmartEnum.Generators;

using Microsoft.CodeAnalysis;

[Generator(LanguageNames.CSharp)]
public sealed class SmartEnumAttributeGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context) => context
		.RegisterPostInitializationOutput(output => output.AddSource("SmartEnumAttribute.g.cs", """
				// <auto-generated />
				namespace SmartEnum;
				
				using System;

				[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
				internal sealed class SmartEnumAttribute<TKey> : Attribute
				{
					public string KeyName { get; }

					public SmartEnumAttribute(string keyName) => this.KeyName = keyName;
				}

				/// <summary>Excludes state from generated constructors, factories and flattened data. Initialize it in user code.</summary>
				[AttributeUsage(AttributeTargets.Field | AttributeTargets.Property, Inherited = false)]
				internal sealed class SmartEnumIgnoreAttribute : Attribute { }

				/// <summary>Copies a computed property's value to flattened data. It is not used during restoration.</summary>
				[AttributeUsage(AttributeTargets.Property, Inherited = false)]
				internal sealed class SmartEnumSnapshotAttribute : Attribute { }

				/// <summary>Maps an external constructor argument to a readable member on the root or its parent.</summary>
				[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
				internal sealed class SmartEnumParentDataAttribute : Attribute
				{
					public string ParameterName { get; }
					public string MemberName { get; }
					public SmartEnumParentDataAttribute(string parameterName, string memberName)
						=> (this.ParameterName, this.MemberName) = (parameterName, memberName);
				}
				"""));
}